### ISSUE TITLE
Auto-generate CommandID for newly created commands in RibbonDesigner

### ISSUE THREAD

**Issue by joachimmarder** [TurboPack/RibbonFramework#103]
Without an explicitly defined CommandID the order of the command in the XML file decides about its command id. This causes the CommandID to be volatile, which is bad as they are used to identify the command in the quick access toolbar.

**Comment by SaschaSchaefer** [comment]
Should we add a "Auto Generate IDs for all commands" function as well, so that existing markup XMLs can be updated accordingly?

Otherwise, newly created commands would potentially override IDs for existing commands, which do not have explicit IDs set, yet.

**Comment by joachimmarder** [comment]
> Should we add a "Auto Generate IDs for all commands" function as well, so that existing markup XMLs can be updated accordingly?

Yes, I guess that wouldn't hurt since its use stays optional.

>   newly created commands would potentially override IDs for existing commands, which do not have explicit IDs set

That should happen as long as newly created commands are to the end by default. For existing projects (that do not have all CommandIds defined) there's also no difference to the current situation, in which this happens as well in case new command are not added at the end.
