### ISSUE TITLE
Settings save/load should be decoupled from the component

### ISSUE THREAD

**Issue by gabr42** [TurboPack/RibbonFramework#13]
While a new user might appreciate that ribbon state is automatically stored/preserved, the current implementation doesn't allow any flexibility in that manner. We are, for example, storing ribbon configuration in registry, not in file system, and with the current implementation we cannot prevent TUIRibbon from automatically doing its save/restore magic parallel to ours.

I propose making the following changes:
- RibbonSettingsFilePath is determined once when component is instantiated and not on every access so the application can overwrite the setting.
- Options property should be added which would contain a set of configuration options TUIRibbonOptions, initially consisting of one option: roAutoPreserveState. Initially this option can be enabled to preserve the backwards compatibility. Auto store/preserve magic would be bypassed if this options is not set.

I can implement these changes if they make sense. [I will certainly disable the automatic save/restore in my fork as it gives me problems.]

**Comment by joachimmarder** [comment]
> I can implement these changes if they make sense. 

Yes, that would be welcome. To me it seems that the roAutoPreserveState should be sufficient to achieve your goal.

**Comment by gabr42** [comment]
My goal, yes. But somebody else may want to configure storage path while leaving the automatic save/restore intact.

**Comment by joachimmarder** [comment]
> RibbonSettingsFilePath is determined once when component is instantiated and 
> not on every access so the application can overwrite the setting.

The getter GetRibbonSettingsFilePath() is implemented lazy, so its value is determined only once in case it is empty. Did I miss something?

**Comment by gabr42** [comment]
You are correct, I misread the code. I'll just add the option, then.

**Comment by gabr42** [comment]
Created pull request #14.

**Comment by gabr42** [comment]
I'm tired fighting with github :( If you know how to merge it, the commit is here: https://github.com/gabr42/RibbonFramework/commit/ddf29ed03827541dfd4115e20f72c4321a3b328c?diff=split

I'll try to create a proper pull request later in the day, if I can find the time.

**Comment by gabr42** [comment]
Finally did it! Pull request #16.
