### ISSUE TITLE
Building the ribbon files is slower than in V1.0

### ISSUE THREAD

**Issue by joachimmarder** [TurboPack/RibbonFramework#18]
Building the ribbon files in the Designer is significantly slower than in V1.0, as reported by @gabr42 

Most of the time is consumed inside the foreach-loop of the Powershell script. Ideas to improve performance:
  * Split string instead of using regex
  * Assemble output file content in memory instead of appending each line to the file

**Comment by joachimmarder** [comment]
The PowerShell command `Add-Content` seems to be the main culprit:
http://sqlblog.com/blogs/linchi_shea/archive/2010/01/04/add-content-and-out-file-are-not-for-performance.aspx

**Comment by joachimmarder** [comment]
Now using System.IO.StreamWriter

**Comment by gabr42** [comment]
I tested the new version (new binary, new .ps1) and now nothing happens ... It says "Starting the resource compiler" and ... nothing. Waited for two minutes and preview didn't appear, then I killed the designer.

**Comment by joachimmarder** [comment]
I cannot confirm this at the moment. I made a fresh checkout and tested with the sample "02 Text Pad with Action List" that worked for me several times.

I experienced such hangs earlier, before I touched the code, but I was unable to reproduce them in a deterministic way. The hangs occurred in ReadFile() which reads the stdout of the called external command line tools.

>  then I killed the designer.

Was the PowerShell script still running too?

**Comment by gabr42** [comment]
> Was the PowerShell script still running too?

Hmmm, didn't check, sorry.

**Comment by joachimmarder** [comment]
I reworked the code that reads the stdout pipe. Would you mind trying again?

**Comment by gabr42** [comment]
Still hangs. I also didn't see any child process as I would expect (powershell). I'll try to debug the problem.

**Comment by joachimmarder** [comment]
> I'll try to debug the problem

That would be great. In the rare cases I saw the problem the process was stuck in the Windows API call ReadFile() that reads the StdOut of the child process. Is this the same in your case?

**Comment by joachimmarder** [comment]
HI Primož.

> I'll try to debug the problem

Any news on that issue?
