### ISSUE TITLE
Sample projects with actions don't respond to mouse clicks

### ISSUE THREAD

**Issue by gtclewis** [TurboPack/RibbonFramework#2]
Project: "TextPad" In High Level folder
Ribbon does not respond to mouse clicks.
Delphi XE8
The OnCommandCreate event (TFormMain.RibbonCommandCreate in the project) is never fired. Stepping through the code I noticed in unit UIRibbon in procedure TUIRibbon.DoCommandCreated the line

 if not Assigned(Self.RibbonMapper) or not Self.RibbonMapper.TryGetItem(pCommand.CommandId, lMarkupItem) then // Get the corresponding TAction for the given Ribbon command
    exit; 

always exits because RibbonMapper is always nil. It appears that this event must fire to be able to link the ribbon to the Delphi actions.

**Comment by joachimmarder** [comment]
Please also see issue #1, not all sample projects are yet converted from V1 to V2.
But there was indeed a bug for project not using the new ribbonmapper mechanism.

**Comment by gtclewis** [comment]
Thank you,

Just starting out with it. Very impressive!

**Comment by gtclewis** [comment]
Another question,

According to the documentation the uicc files are included.

Designer\Bin: this directory contains the pre-compiled version of the 
Ribbon Designer. Just start RibbonDesigner.exe to launch it. This 
directory also contains the Microsoft Ribbon Compiler (UICC.exe and 
UICCDLL.dll).

I'm using Windows 8.1 and don't have these files anywhere including that 
directory. Can I get them somewhere? I just installed the 8.1 SDK and 
they still aren't there.

Thanks
