### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION in UIRibbon.dll

### ISSUE THREAD

**Issue by mwintex** [TurboPack/RibbonFramework#23]
Hi,

we got an access violation in Module: UIRibbon.dll
Code: C0000005 (EXCEPTION_ACCESS_VIOLATION)

Any idea?

Best regards

**Comment by joachimmarder** [comment]
Can you post the full call stack please?
Which version are you using?
Are you able to replicate the error with one of our sample projects?

**Comment by mwintex** [comment]
Hi,

in the attachment you can find an image of the stack.
We are using the lastest version of the RibbonFramework.
The UIRibbon.dll Version is 6.1.7601.17514
With the sample projects everything works fine!

![stack](https://cloud.githubusercontent.com/assets/16719194/12387520/719d8422-bdcd-11e5-80f9-b82a4c878129.png)

**Comment by joachimmarder** [comment]
> The UIRibbon.dll Version is 6.1.7601.17514

This DLL ist part of the Windows operating system and our components are a wrapper around this DLL. Are you using the latest source of these components from GitHub?


> With the sample projects everything works fine!

I'm sorry but I don't think I can help here without steps for reproducing the problem or a sample project that provokes this error.

**Comment by joachimmarder** [comment]
Is there any news on this issue?

> With the sample projects everything works fine!

You could then try using a ribbon from one of our sample projects, e.g. Samples\High Level\01 Simple Ribbon\Ribbon\SimpleRibbonUI.pas  and see if then the error disappears. That way we know if the problem is related to the ribbon resources or to the application.

**Comment by mwintex** [comment]
I guees the problem is caused by our application. We will use another Ribbon Control to solve the problem. Thank you very much for your efforts and assistance.

**Comment by joachimmarder** [comment]
> I guess the problem is caused by our application.

Did you get an idea why exactly?

**Comment by mwintex** [comment]
Delphi says "unknown exception". That's all! We did not spent more time to find the problem.
