### ISSUE TITLE
Ribbon designer freezes during build

### ISSUE THREAD

**Issue by joachimmarder** [TurboPack/RibbonFramework#24]
The Ribbon designer may freeze during a build. The freeze occurs in the call of ReadFile() in  RibbonCompiler.TRibbonCompiler.Execute().

**Comment by 7profy** [comment]
Issue #24 freezes again.
(Using Delphi XE8, Win7 64x, binary designer file)

**Comment by joachimmarder** [comment]
I was no longer able to reproduce the freeze, but I refined the code a bit more. Could you please try again?

If it still freezes, it would be great if you could run the Designer from the Delphi IDE and post the call stack of the main thread ("Run > Program Pause", "View > Debug Windows > Call Stack"). Maybe you can debug the designer to see why it freezes. I suspect TRibbonCompiler.Execute().

**Comment by 7profy** [comment]
Ok. I'll try a bit later

**Comment by 7profy** [comment]
Procedure TRibbonCompiler.Execute() freeze at row:
if PeekNamedPipe(ReadPipe, @Buffer[0], SizeOf(Buffer) div 10, @BytesRead, @BytesAvail, @BytesLeft) then // Read smaller chunks for continuous output

ReadPipe and WritePipe created well (not null), other vars are good.
May be security attributes bad?

**Comment by 7profy** [comment]
CmdLine generate correctly. Execute at external bat-file value of CmdLine  - successfully.

**Comment by 7profy** [comment]
MSDN tell us:
WARNING: PeekNamedPipe() can hang up and will not return immediately when the read end of an anonymous pipe has zero bytes in the pipe.
(https://msdn.microsoft.com/en-us/library/windows/desktop/aa365779(v=vs.85).aspx)

**Comment by 7profy** [comment]
I suppose the bug at CreateProcess.
If I switch on powershell window (StartupInfo.wShowWindow := SW_NORMAL;) I see black window - no messages.

**Comment by joachimmarder** [comment]
Without using STARTF_USESTDHANDLES we cannot read the output of the called program and so the freezing code does not do anything. Does not seem an option to me.

I reverted yesterday's changes and interestingly the freeze I was able to reproduce yesterday does no longer occur. Now I can't debug.  :-(

Would you mind trying with a smaller buffer, e.g. 32 bytes instead of 1024?

**Comment by joachimmarder** [comment]
With a larger buffer (100KB) I got the freezes too, but Interestingly only with nor debugger attached. So I still wasn't able to debug this. I have now reduced the buffer size for the continuous reads from the pipe and use a larger buffer for the final read.

**Comment by joachimmarder** [comment]
Hopefully this issue is now fixed. It will be reopened if it occurs again.

**Comment by 7profy** [comment]
I find out that hang only 'powershell'. Other console apps works fine (for example 'ping')

**Comment by joachimmarder** [comment]
> I can't understand why PeekNamedPipe freezes.

That's exactly the point! In the cases I saw the freeze, it was ReadFile() that freezes. Have you tried on another PC?

We used PowerShell so that we can build the ribbon resources in makefiles and build scripts.

**Comment by 7profy** [comment]
Finded strange solution:
At TRibbonCompiler.Execute set StartupInfo.hStdInput := 0; //Instead ReadPipe;

But it require add ReadFile after PeekNamedPipe.

**Comment by 7profy** [comment]
On another PC not freezes.

**Comment by joachimmarder** [comment]
> UPD2. If missing some files (for example Generate.Ribbon.Markup.pas.ps1) loggin 
> window show message with broken chars for non-english systems (suppose DOS charset)

Yes, PowerShell indeed uses the OEM codepage for its output, not the system default code page. I have now corrected the code (but not updated the EXE yet).

**Comment by joachimmarder** [comment]
> UPD. Original designer on another PC freezes too!!!

Yes, I also find the freezes coming and going. I have no idea yet.

**Comment by joachimmarder** [comment]
> Finded strange solution:
> At TRibbonCompiler.Execute set StartupInfo.hStdInput := 0; //Instead ReadPipe;
> But it require add ReadFile after PeekNamedPipe.

Could you please post your code?

**Comment by 7profy** [comment]
Using your last update. Function TRibbonCompiler.Execute:

1. At procedure LogBuffer replace `S := GetString(Buffer);` to `S := GetString(Buffer) + #13#10;`

2. Replace `StartupInfo.hStdInput := ReadPipe;` to `StartupInfo.hStdInput := 0;`

3. My read process:
```
       if PeekNamedPipe(ReadPipe, @Buffer[0], BuffSize-1, @BytesRead, @BytesAvail, @BytesLeft) then
          if BytesAvail > 0 then
          begin
            ReadFile(ReadPipe, Buffer, BytesAvail, BytesRead, nil);
            LogBuffer;
          end;
```
Don't see the reason to read pipe by small chunks.

**Comment by joachimmarder** [comment]
Looks god, thanks. Changes are committed.

**Comment by 7profy** [comment]
Remove first (BytesAvail > 0) at
```
        if PeekNamedPipe(ReadPipe, @Buffer[0], Length(Buffer) -1, @BytesRead, @BytesAvail, @BytesLeft) and (BytesAvail >0) then
        begin
          if (BytesAvail > 0) and ReadFile(ReadPipe, Buffer[0], BytesAvail, BytesRead, nil) then
            LogBuffer();
        end;//if
```

**Comment by 7profy** [comment]
At function TRibbonCompiler.Compile add 
    `DoMessage(mkInfo, sLineBreak);`
before
    `DoMessage(mkInfo, RS_STARTING_DELPHI_COMPILER);`

**Comment by joachimmarder** [comment]
Thanks, proposed changes are done.
