### ISSUE TITLE
ver 2.1, Installing Package\UIRibbonPackage.dproj errors

### ISSUE THREAD

**Issue by eives** [TurboPack/RibbonFramework#25]
Unable to load project
UIRibbonPackage.dproj Only one top level element is allowed in an XML Document.
Line 2: <VersionInfoKeys Name="restoreAnyVersion">
I'm not sure how to fix this

**Comment by joachimmarder** [comment]
Which version of Delphi are you using?

Di you use the package "Package\UIRibbonPackage.dproj" or  "Package\Delphi\UIRibbonPackageDD.dproj"?

**Comment by eives** [comment]
Delphi 2007
I used the UIRibbonPackage.dproj and then tried the UIRibbonPackageDD.dproj. They both fail about the same way, just different locations in the script.

**Comment by joachimmarder** [comment]
I'm sorry, Delphi 2007 is not supported. V2 requires Delphi XE2 or higher. The original V1 requires Delphi 2010 or higher.

**Comment by eives** [comment]
Thank you for looking into this, just wish there was a version supported section in the read me, would not have spent a couple of days on this issue. 
Thanks again for your time.

**Comment by joachimmarder** [comment]
> just wish there was a version supported section in the read me, 
> would not have spent a couple of days on this issue. 

I am sorry for that and you are absolutely right. This was somehow lost when I migrated the project to GitHub and started V2.0. I have now added the supported versions.
