### ISSUE TITLE
Ribbon Compiler does not build anything with Windows 7 SDK

### ISSUE THREAD

**Issue by MarcusCalidus** [TurboPack/RibbonFramework#26]
Hi,

I recently had to change from my development engine (Windows Server 2012 with Win 8.1 SDK - English) back to a Windows 7 (with Windows 7 SDK - German) engine. 
Thereupon I recognized that the ribbon compile process does not generate any file output on my Windows 7 machine. It works flawlessly under Windows 8.1 SDK. Is there a chance to get some debug output from the powershell script?
Compiler is from Delphi 10 Seattle

- After creating a new project the compile process starts
- nothing is created except for the .dpr file

![image](https://cloud.githubusercontent.com/assets/4113366/12816073/8f13c964-cb4a-11e5-92f2-7d6db96d2ec2.png)
![image](https://cloud.githubusercontent.com/assets/4113366/12816081/a0057362-cb4a-11e5-8bba-38a166d35042.png)

Any ideas?

cheers
Marco

**Comment by joachimmarder** [comment]
Are you using the latest V2.1.2 of the Ribbon Framework for Delphi?
Does the problem also occur with one of the included sample projects?

**Comment by MarcusCalidus** [comment]
Hi Joachim,

I am using the latest version from git 2.1.2.
Upon compiling the sample project I see this

![image](https://cloud.githubusercontent.com/assets/4113366/12845421/00677eb0-cc06-11e5-830f-5c9da67cff25.png)

**Comment by joachimmarder** [comment]
In the subfolder "Ribbon" of each of our sample projects there is a "CompileRibbon.bat". Could you please run it and post the output here?

**Comment by MarcusCalidus** [comment]
![image](https://cloud.githubusercontent.com/assets/4113366/12847932/fc4eae82-cc16-11e5-8785-746299fef382.png)

**Comment by MarcusCalidus** [comment]
sorry, I found the trick. just had to put SDK bin into the path variable. Then it worked. You may close the issue.

**Comment by joachimmarder** [comment]
I still don't understand why the Designer / the PowerShell build script did not find UICC.exe. I think it should have.

Was the path shown in your screenshot of the Ribbon designer correct and valid?

**Comment by joachimmarder** [comment]
I think I found the reason and fixed it for the next release.
