### ISSUE TITLE
SelectedTabChanged

### ISSUE THREAD

**Issue by guetin** [TurboPack/RibbonFramework#28]
Is there any way to catch SelectedTabChanged on the Ribbon ?

**Comment by joachimmarder** [comment]
The Issues section is for reporting bugs and featrue requests, this is not a support forum. Please try to get support e.g. at StackOverflow.com.

I don't think that this is possible. In case the ribbon API supports this, please post a link to the appropriate function and I will try to wrap it in a Delphi event.

**Comment by MarcusCalidus** [comment]
This will not work with the current implementation since it is supported from Win8 upwards.

https://msdn.microsoft.com/en-us/library/windows/desktop/hh973498(v=vs.85).aspx

**Comment by guetin** [comment]
Thank you for your answers.
