### ISSUE TITLE
Support dynamically changing images

### ISSUE THREAD

**Issue by ghmrs356** [TurboPack/RibbonFramework#31]
I'm not quite sure why, but it seems really difficult to change images for a command. First, the SmallImage, LargeImage properties are nil unless NO image is assigned to the command. If you assign an image at design time, these member are nil.

Also, the TUICommand.OnUpdateImage event is utterly confusing (and I think really not working). How is one supposed to update the image using this callback? There's now way to pass a new image out of it, is there? What's NewValue supposed to contain? There might be a good reason but it's a little difficult to understand.

What I would like to do is proactively set images like I change action captions which Just Works(tm).

I've experimented a little and it seems I can just make the Small/Large/Image properties writable with a setter like this:
```Pascal
procedure TUICommand.SetSmallImage(const Value: TUIImage);
begin
  if (FSmallImage <> Value) then begin
    FSmallImage.Free;
    FSmallImage := Value;

    FFramework.InvalidateUICommand(FCommandId, [UIInvalidationsProperty], @UI_PKEY_SmallImage);
  end;
end;
```
When I want to change the image I just load a new TUIImage and set it. Of course this should be much more streamlined and abstracted but it works just like I wanted.

Is there a reason why images are not writable?

**Comment by joachimmarder** [comment]
I spoke with the original author and he said that there is no specific reason for the images being not writable. He also says that your proposed code looks pretty OK. You can find similar code in a C# wrapper:

https://searchcode.com/codesearch/view/9937506/

Making images writable would allow us to not only assign caption, hint etc. from a VCL action, but also the small and large image. Currently I have many images twice in my project: Once in the ribbon resources and a second time in a VCL imagelist in case the image is used elsewhere too, e.g. in a popup menu.

**Comment by ghmrs356** [comment]
Thanks for looking into this. I see the same problem with duplicate images, but do the Delphi image lists work with 32 bit alpha bitmaps and if not, how are you going to solve the transparency issue in the ribbon?

**Comment by joachimmarder** [comment]
Yes, VCL TImageList can handle 32Bit ARGB images since Delphi 2010. You just need to set the property ColorDepth to the value cd32Bit.

**Comment by joachimmarder** [comment]
This has been implemented. Images are now taken from a VCL actions automatically if a valid ImageIndex and ImageList isavailable, the latter through a TActionManager. This is a breaking change.

**Comment by joachimmarder** [comment]
We should assign images from VCL actions only in case the ribbon element does not have an image assigned.
