### ISSUE TITLE
TUIRibbon.LoadSettings and SaveSettings leak TStreamAdapter

### ISSUE THREAD

**Issue by ghmrs356** [TurboPack/RibbonFramework#32]
The current implementation leaks the TStreamAdaptor:

```Pascal
function TUIRibbon.SaveSettings(const Stream: TStream): Boolean;
var
  ComStream: IStream;
begin
  Result := Assigned(FRibbon);
  if (Result) and fLoaded then
  begin
    ComStream := TStreamAdapter.Create(Stream, soReference);
    Result := Succeeded(FRibbon.SaveSettingsToStream(ComStream));
  end;
end;
```
 I suggest to change it to something like this

```Pascal
function TUIRibbon.SaveSettings(const Stream: TStream): Boolean;
var
  ComStream: TStreamAdapter;
begin
  Result := Assigned(FRibbon);
  if (Result) and fLoaded then
  begin
    ComStream := TStreamAdapter.Create(Stream, soReference);
    try
        Result := Succeeded(FRibbon.SaveSettingsToStream(ComStream));
    finally
        ComStream.Free;
    end;
  end;
end;
```
Same for the LoadSettings() method.

**Comment by joachimmarder** [comment]
ComStream is of type IStream and so reference counted.  It is going to be freed when the ref count reaches 0.

Ref counted instances should not be freed explicitly.

**Comment by ghmrs356** [comment]
Well FastMM4 certainly disagrees with that, it reports a leak of TStreamAdapter.

**Comment by joachimmarder** [comment]
I tested with MadExcept, XE8 and the sample project "07 Text Pad with Action List". It does not report a leaked TStreamAdapter. It reports another mem leak though I will open a separate issue for this.

**Comment by ghmrs356** [comment]
I think you are right, as I got a crash for over-releasing the stream adapter. Sorry for the noise!
