### ISSUE TITLE
No Compiler messages generated.

### ISSUE THREAD

**Issue by Andyk123** [TurboPack/RibbonFramework#33]
Message handler only assigned if the application receives a file parameter.

Handler is not assigned if the RibbonDesigner.exe is run without parameters.

FCompiler.OnMessage := RibbonCompilerMessage 

needs to be moved in the TformMain.create event.

**Comment by joachimmarder** [comment]
Thanks for your contribution. Issue has been fixed in source code, the fix will be part of the next release.
