### ISSUE TITLE
ColorPicker not displaying any modifications

### ISSUE THREAD

**Issue by ghmrs356** [TurboPack/RibbonFramework#36]
I have a drop down color picker in my ribbon XML, configured like this:

```XML
  <DropDownColorPicker CommandName="rcmdTEFormatColor" 
                       ColorTemplate="StandardColors" 
                       ChipSize="Large" 
                       IsAutomaticColorButtonVisible="false" 
                       IsNoColorButtonVisible="true" 
                       Columns="8" 
                       StandardColorGridRows="6" />
```

in the OnCommandCreate event, I attempt to modify the anchor command as follows

```Pascal
procedure TMyForm.OnRibbonCommandCreate(const Sender: TUIRibbon; const Command: TUICommand);
const colorCount = 88;
var cmd:TUICommandColorAnchor;
    i: Integer;
    colors: TArray<TColor>;
    tooltips: TArray<String>;
begin
  if not ((Command.CommandId = myCommandId) and (Command is TUICommandColorAnchor)) then
    exit;
 
  cmd := Command as TUICommandColorAnchor;

  SetLength(colors, colorCount );
  SetLength(tooltips, colorCount );

  for i := 0 to (colorCount -1) do begin
    colors[i] := clBlue;
    tooltips[i] := 'True Blue';
  end;

  cmd.OnExecute := OnColorPickerExecute;
  cmd.ColorType := ctRgb;
  cmd.Color := clRed;

  cmd.StandardColors := ribbonColors;
  cmd.StandardColorTooltips := ribbonColorTooltips;

  cmd.MoreColorsLabel := 'Add Color';
end;
```

Yet it does not show any of my colors or tool tips, nor does is show the color I set, it only shows the modified MoreColorsLabel. And the OnColorPickerExecute event handler is being called correctly.

Any ideas, I must be missing something obvious?

**Comment by joachimmarder** [comment]
Can the sample project "High Level\03 DropDown Color Picker" be modified so that it shows the issue?

**Comment by ghmrs356** [comment]
I continued to investigate this one and found out that StandardColors and StandardColorTooltips can't be set within the OnCommandCreate handler for the color anchor in question. I haven't looked into whether this is a framework (Windows) issue or something in the Delphi wrapper. I assume the control isn't full initialized or simply not ready to be customized yet. Postponing the initialization until after the event has been called does the trick.
