### ISSUE TITLE
App crashes on Windows 7

### ISSUE THREAD

**Issue by ghmrs356** [TurboPack/RibbonFramework#37]
Any idea why my app might crash in the resource loading step of the ribbon with "There was a problem loading resource APPLICATION" when started on Windows 7 (ultimate)? Does Windows 7 have any prerequisites that have to be met? My ribbon is rather complex, the resource file is about 10MB, all images are 32 bit bitmaps, not PNG.

**Comment by ghmrs356** [comment]
Not a clue what it is yet, but the TextPad sample application starts up fine, so does my app without ribbon, so it definitely is the ribbon and it is something in my ribbon setup Windows 7 apparently can't handle.

I would be most grateful for any pointers as to what this might be.

**Comment by ghmrs356** [comment]
OK, now I tried the TextPad sample with my complex ribbon (using RibbonMarkup.pas and res from my project without changes) and it loads fine.

**Comment by joachimmarder** [comment]
>  Does Windows 7 have any prerequisites that have to be met?

Windows 7 does not have any prerequisites as far as I know.

> Any idea why my app might crash in the resource loading step of the ribbon with "There was a problem loading resource APPLICATION" when started on Windows 7 (ultimate)?

Is the ribbon resource properly included in the EXE? Please check this with a resource editor.

And one more note: This is not a support forum, this is a bug tracker. Please use websites like stackoverflow.com to get support. In case you identified a bug or would like to suggest an enhancement, this is the right place. In case of a bug report please include steps how to reproduce the bug, ideally based on one of the sample projects.
