### ISSUE TITLE
Can't biuld/preview ribbon

### ISSUE THREAD

**Issue by Clarc1984** [TurboPack/RibbonFramework#38]
I can't build any ribbon, even from samples folder. When i try to build or preview ribbon, text field on the button of ribbondesigner.exe blink ones on red and nothing else happen. I use Delphi XE8 on Windows 10 Pro and my path from ribbondesigner are:
C:\Program Files (x86)\Windows Kits\10\bin\x86\uicc.exe
C:\Program Files (x86)\Embarcadero\Studio\16.0\bin\DCC32.EXE
they don't detect automatically. Does path for uicc.exe should contain "Windows Kits\10"? Downloaded Windows SDK was for Windows 7.

**Comment by joachimmarder** [comment]
> When i try to build or preview ribbon, text field on the button of 
> ribbondesigner.exe blink ones on red and nothing else happen.

Are you sure that no error message like "Cannot find UICC.exe." is added to the text field? Can you attach a screenshot please?

> they don't detect automatically

Have you tried setting them explicitly at "File > Settings"?

> Downloaded Windows SDK was for Windows 7.
> Does path for uicc.exe should contain "Windows Kits\10"? 

As far as I know the Win7 SDK normally does not contain "10" in the path. Sounds more like the Win10 SDK to me.

**Comment by Clarc1984** [comment]
> Are you sure that no error message like "Cannot find UICC.exe." is added to the text field? Can you attach a screenshot please?

There is no error. I'm sending link to video.

> Have you tried setting them explicitly at "File > Settings"?

I set it manually but no result.

> As far as I know the Win7 SDK normally does not contain "10" in the path. Sounds more like the Win10 SDK to me.

I download and install SDK from link in ribbon designer. File (ISO) was describe as Windows 7 SDK but after installation it install as Windows Kits\10.

Link to video: https://drive.google.com/open?id=0B4kJognoLljVc0k3cmpRNzk2YXM

**Comment by joachimmarder** [comment]
Does it change anything if you use the new [release V2.1.5](https://github.com/TurboPack/RibbonFramework/archive/2.1.5.zip)?

Maybe there is an issue with PowerShell, which is used for building the ribbon. What happens if you execute "RibbonFramework\Samples\High Level\07 Text Pad with Action List\Ribbon\CompileRibbon.bat"?

**Comment by Clarc1984** [comment]
2.1.5 don't change anything BUT
1) I recognize that SDK for Windows 7 was not install properly. I had to download SDK for x64 from this link [http://download.microsoft.com/download/F/1/0/F10113F5-B750-4969-A255-274341AC6BCE/GRMSDKX_EN_DVD.iso](url)
2) To install SDK on Windows 10 i had to remove first MS Redistributable c++ 2010 x86/x64
3) Then i try to execute script from Your post and start to repair errors
4) There was problem with powershell - on Windows 10 / Serwer 2012 running scripts should be allowed first, instruction how to do this is on this site [https://absolute-sharepoint.com/2014/03/change-powershell-machinepolicy-execution-policy-windows-server-2012r2.html](url)
5) Then I had problem with Generate.Ribbon.Markup.pas.ps1, I had to add path for rc to system variables to run script without errors and get pas and res files
6) Now script run manually is working but when I want to build/preview something with ribbondesigner I got same situation as before - red blink and nothing more

**Comment by joachimmarder** [comment]
> I recognize that SDK for Windows 7 was not install properly. 

You only need the files UICC.EXE and UICCDLL.DLL, which you can copy next to the RibbonDesigner.exe. Due to copyright restriction we cannot include the files in the archive.

> There was problem with powershell - on Windows 10 / Serwer 2012 running scripts should be allowed first,

Indeed, in the .BAT-files the command line option -ExecutionPolicy Bypass was missing, which I have changed now.

>  I had to add path for rc to system variables to run script without errors and get pas and res files

RAD Studio installer typically takes car of that.

**Comment by joachimmarder** [comment]
> Now script run manually is working but when I want to build/preview something with ribbondesigner I got same situation as before - red blink and nothing more

Sorry, I have no clue what could be going on. The RibbonDesginer is included in full source code and should compile without prerequisites on XE8. Please run in in the debugger and set a breakpoint at the beginning of the method TRibbonCompiler.Compile() in the unit "RibbonCompiler.pas". May you can find out what's going on and we can improve error handling based on your findings.

**Comment by Clarc1984** [comment]
I resolve it :) Error occur at powershell execution. When i try to manually execute generated code i got message that powershell is not recognize. I had to add system variables path to powershell folder and now everything is working. In case of future error i suggest add full path to files (powershell, rc etc.). Thanks for help.

**Comment by joachimmarder** [comment]
Strange. I just mocked this situation and ended up with an error message in the log window. I have now improved the error message.
