### ISSUE TITLE
How to change language used in the ribbon?

### ISSUE THREAD

**Issue by Brnoch** [TurboPack/RibbonFramework#41]
This is not an issue...
I'd like to know how to change dynamically the language used in the ribbon.
Based on this webpage (http://stackoverflow.com/questions/14917302/change-default-language-on-ribbon-control), I think that it is possible if the desired windows language pack is installed on the machine, but I don't know how to implement it in Delphi.
Can anyone help me about it? Thanks in advance!

**Comment by joachimmarder** [comment]
The solution in this stackoverlfow posting suggests calling the API function `SetThreadPreferredUILanguages()`, which should be no problem in Delphi.

Please note that this is a bug tracker, and not a support forum. Asking this question e.g. on stackoverflow.com is more appropriate and might generate an answer faster.

**Comment by Brnoch** [comment]
Thanks a lot!

**Comment by joachimmarder** [comment]
One more note on this: It seems that the prototype for `SetThreadPreferredUILanguages()` in Delphi's "WuinApi.Windows" unit is wrong, the third paramter is missing (checked with Delphi 10.1 Berlin). It should be:

    function SetThreadPreferredUILanguages(dwFlags: DWORD; pwszLanguagesBuffer: PWideChar; pulNumLanguages: PULONG): BOOL; stdcall; external kernel32 name 'SetThreadPreferredUILanguages' delayed;
