### ISSUE TITLE
Combobox text is not updated

### ISSUE THREAD

**Issue by aj-brasaca** [TurboPack/RibbonFramework#42]
The combobox component that is not part of the active tab when the program is loaded is not updated. For example, I define that some strings should already appear as default (be shown) when the tab to which they belong were selected. However, the part of the text remains blank. Only by clicking another tab and returning to this is that the user interface is updated. I put a combo box on the default tab that appears when the program is loaded and it did not happen.

![ribbon1](https://cloud.githubusercontent.com/assets/8443207/16393399/fea8b16a-3c86-11e6-8f0a-f0b9ac05972f.png)
![ribbon2](https://cloud.githubusercontent.com/assets/8443207/16393535/aafbfa58-3c87-11e6-98d0-4d5d43cea87a.png)
![ribbon3](https://cloud.githubusercontent.com/assets/8443207/16393593/c60f691a-3c87-11e6-9ba4-28f84c3ad6ec.png)

**Comment by joachimmarder** [comment]
Can provide a sample project that illustrates the problem, or steps how to modify one of the included sample projects to replicate the issue?

**Comment by aj-brasaca** [comment]
Unfortunately, I try to send you the executable through this site but it is refusing to load the zip file. Send me please your email address.

**Comment by aj-brasaca** [comment]
Joachim,

Below is the procedure that populates the combobox with the itens shown in the figure.

procedure TfrmPrincipal.PopulateIniciarVisao;
const
  VisaoIds : array[0..6] of Integer = (LIST_VISAO_1, LIST_VISAO_2, LIST_VISAO_3, LIST_VISAO_4,
                                       LIST_VISAO_5, LIST_VISAO_6, LIST_VISAO_7);

var
  I : integer;
  Item : TUIGalleryCollectionItem;
begin
  FcmdIniciarVisao.Items.BeginUpdate;
  try
    for I := 0 to Length(VisaoIds) - 1 do
    begin
      Item := TUIGalleryCollectionItem.Create;
      Item.LabelText := CreateStringFromResource(VisaoIds[I]);
      FcmdIniciarVisao.Items.Add(Item);
    end;
  finally
    FcmdIniciarVisao.Items.EndUpdate;
  end;
  FcmdIniciarVisao.RepresentativeString := 'Nenhuma';
  FcmdIniciarVisao.SelectedItem := 0;

end;


![combobox](https://cloud.githubusercontent.com/assets/8443207/16415893/f827032a-3d15-11e6-9a93-57ad52e4ebaa.png)

**Comment by joachimmarder** [comment]
> Unfortunately, I try to send you the executable through this site

I don't need an executable, I need a project in source code that I can debug in the IDE.

**Comment by aj-brasaca** [comment]
Ok ! How can I send you the code ? Because the site is not accepting  zip files.

**Comment by joachimmarder** [comment]
Have you tried attaching them unzipped? 
How many units does your project have?

**Comment by aj-brasaca** [comment]
It seems that site only accepts file types PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF or ZIP (wich not works !). I try upload .pas but refused. My project contains only one unit. Do you also will not need the resource files and project images? The zip with all files has 2.12 MB.

**Comment by joachimmarder** [comment]
> or ZIP (wich not works !)

I have no idea why attaching ZIP should not work. Please upload it e.g. on http://senduit.com/ and attach the link. I will try attaching the 

> Do you also will not need the resource files and project images

Please include anything that is need to compile and run the project without error.

**Comment by aj-brasaca** [comment]
If something is wrong, let me know. The link:

https://1drv.ms/u/s!AuSTIeosjoqoimrNwuXQF9h3FqtW

**Comment by aj-brasaca** [comment]
Sorry. Try this...

https://1drv.ms/u/s!AuSTIeosjoqoimvLL7D9PuUJjCrS

**Comment by aj-brasaca** [comment]
Sorry... Try this:

https://1drv.ms/u/s!AuSTIeosjoqoimvLL7D9PuUJjCrS

**Comment by aj-brasaca** [comment]
It's not working... Once work I warn you ...

**Comment by aj-brasaca** [comment]
Try this...

https://1drv.ms/u/s!AuSTIeosjoqoim3xQj9Xde5lfBGa

**Comment by joachimmarder** [comment]
I was able to download the file. However, it does not compile. After removing dependencies on the missing units I still get compiler warnings, and when I start the application I get runtime errors.

Which version of the Ribbon Controls for Delphi are you using?
May I suggest that you try modify one of the existing sample projects for reproducing the issue?

**Comment by aj-brasaca** [comment]
I'm using the framework from Bilsen's site . I download it 3 years ago. I'm not using any version of GitHub, yet...

**Comment by joachimmarder** [comment]
I'm sorry, but this site is for V2 and later only.
