### ISSUE TITLE
Action link on TUICommandAnchor does not work

### ISSUE THREAD

**Issue by svenson08** [TurboPack/RibbonFramework#43]
The tutorial should be noted that this instruction classes TUICommandAnchor addition has no additional settings or events to TUICommand. But TUICommand offers ActionLink.

Background is that I would have to perform a action when Tab changing

**Comment by joachimmarder** [comment]
I'm sorry, but I don't understand your comment / issue. Could you please provide some more details? If you think this is a bug in `TUICommandAnchor `, can you please supply a sample project that demonstrates this? Steps to replicate the issue with one of the included sample projects are fine as well.

**Comment by joachimmarder** [comment]
Any news on this? I will close the issue otherwise.
