### ISSUE TITLE
Change to AddToRecentItems for application consistency

### ISSUE THREAD

**Issue by Andyk123** [TurboPack/RibbonFramework#44]
I made this change to give the same operation as other applications.

Currently the recent items list displays the full path to the items, which usually means the actual filename is cut off. Not a very useful if you can't see the name.

This extracts the filename for the lable text and puts the full path into the description, it displays as a tooltip when hovered over.

`procedure TUIRibbon.AddToRecentItems(const pPath: string);
var  lItem: TUIRecentItem;
begin
  lItem := TUIRecentItem.Create;
  lItem.LabelText := ExtractFilename(pPath);
  litem.Description:=pPath;

  fRecentItems.Items.Add(lItem);
end;
`

The RecentItems execute action should be changed to use the description field rather than the labeltext....eg

Openfile(UIRibbon1.GetSelectedRecentItem.Description)

**Comment by joachimmarder** [comment]
I think we should not hard-code this in the component but leave this up to the application. For example: My application [Treesize](http://www.jam-software.com/treesize/) uses the recently items for the scanned path, which are typically short folder paths or drives. For TreeSize this would be a truly breaking change.

On eoption would be to add an optional parameter for the description to `TUIRibbon.AddToRecentItems()`

**Comment by Andyk123** [comment]
Yes the optional description parameter would give the best functionality.

**Comment by joachimmarder** [comment]
Implemented in master.
