### ISSUE TITLE
Problems creating button groups

### ISSUE THREAD

**Issue by Andyk123** [TurboPack/RibbonFramework#45]
What is the correct way to do this ?

I have tried several attempts to get this to work.

I create a group in the view, then add buttons to it OK, but the MS complier always shows errors and refuses to compile it.

I can't see how to create a set of size definitions that compiler will be happy with when button groups are included.

Can you create a tutorial or provide an example in the samples as to how this can be achieved !

Ta

**Comment by joachimmarder** [comment]
> the MS complier always shows errors and refuses to compile it.

It would have been great if you copied the error message. It could be a general limitation fo the Windows Ribbon Framework.

Please also note that this issue tracker is intended to file bugs, it is not a support forum. Please use e.g. [stackoverflow.com](http://stackoverflow.com/) to get support. When submitting bugs, please include all error messages and a sample project or steps how to replicate the problem with one of the included sample projects.

**Comment by Andyk123** [comment]
SOrry didn't know if this is a bug or not.

I used the sample wordpad ribbon and moved Align left/right/centre/justify into a controlgroup.

returned errors from the MScompiler are...

error SC1030 : Group child element 'ControlGroup' does not match expected format for the SizeDefinition control 'Control'.
 error SC1012 : Unable to determine mapping of elements for Group to SizeDefinition 'ParagraphLayout'.
 error SC1009 : Unable to apply Group.SizeDefinition property 'ParagraphLayout'.

The size definitions in ParagraphLayout are grouped for these controls

**Comment by joachimmarder** [comment]
OK, I see that too these error messages too, they come from Microsoft's ribbon compiler. Sorry, I never got an expert in that ribbon XML stuff after taking over the project. There are many constraints in the Windows Ribbon Framework and the only bug in the editor here is most likely that it does not know about all these constraints and does not prevent the user from defining stuff that is invalid.

Google found only one hit for the first error message:
https://msdn.microsoft.com/de-de/library/windows/desktop/dd316918%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

In the end this is a general Windows Ribbon Framework support question, and stackoverflow.com might generate more help.

**Comment by joachimmarder** [comment]
> As a side issue, the compiler always says it built successfully, even when it fails.

This has been fixed meanwhile.
