### ISSUE TITLE
TUICommandColorAnchor.SetColorType corrupts icon

### ISSUE THREAD

**Issue by Andyk123** [TurboPack/RibbonFramework#46]
Calling SetcolorType(ctRGB) corrupts the on screen icon.

The lower half of the associated icon disappears.

Also happens when setting the colour (probably because this also calls SetColorType).

**Comment by joachimmarder** [comment]
Some more details would be appreciated.
Can you describe when and why your are calling `SetColorType()`?
Can you provide a sample project or describe how to modify the TextPad sample project in order to reproduce the problem?

**Comment by Andyk123** [comment]
Scrub that, I have just realised what is happening.

I was using small icons and presetting the color that the dialogs was set to when the commands are created.

Basically the color dialog is used to set the background color of the object the software is operating on.

I was unaware that when the color is selected on this dialog is show in a color  bar beneath the icon. 

When the background color is set, it appears to erase the bottom half of the icon as if it has become corrupted, but in fact it is just the color bar (which becomes apparent when the color is something other than the background color). It is exaggerated when small icons are used as it appears to erase the whole lower half.
