### ISSUE TITLE
Ribbon Designer - Cannot compile ribbon file under windows 10  

### ISSUE THREAD

**Issue by karooma** [TurboPack/RibbonFramework#47]
Hi,
The included power shelll script **Generate.Ribbon.Markup.pas.ps1** cannot be compiled on windows 10. the message windows flashes in red than nothing, no error message either. I tried the xml files in the samples folder but no luck. Windows 10 sdk is installed, ribbon compiler and dcc32 paths set correctly.
Everything works fine under windows 7.

Any ideas, can I bypass the power shell script and generate the ribbonmarkup.pas using an alternate method.

Many thanks for the great component. It almost made regret purchasing Devexpress components.

Karim Kouni.

**Comment by joachimmarder** [comment]
Which version of this component set did you use? V2.1.5 or the GitHub master?

If V2.1.5: Can you please try if the GitHub master or the brand new V2.2 changes anything or brings at least an error message?

**Comment by karooma** [comment]
I can confirm that Build and Preview  do not work in V2.1.5, Githubmaster and V2.2 on windows 10. The messages windows (bottom) flashes in red and then nothing, no error messages.

**Comment by joachimmarder** [comment]
Does the new V2.2.1 change anything especially regarding error messages?

**Comment by karooma** [comment]
This is a screenshot of the error message, Windows 10 sdk installed and powershell permissions set to execute all ps1 scripts.

![error](https://cloud.githubusercontent.com/assets/20535050/17001720/23e9c07c-4ec0-11e6-9e7c-8f99ddeab86f.png)

**Comment by karooma** [comment]
Update:
Looking at the code, the designer code seems to be hard wired to windows 7 settings and that is why it could not find the powershell.exe. As a test, I hard coded the path to powershell exe in the TRibbonCompiler.Compile method on my system and everything is now in order. 

![compiler-success](https://cloud.githubusercontent.com/assets/20535050/17026166/1a57bf4a-4f57-11e6-92ae-a417635c5a01.png)
 
As a side note, I believe the designer code, can be made much simpler by adding an option to specify the path to powershell and rc instead of doing a myriad of checks for powershell, bds and the likes. Please see issue #51 for details.

That is beging said, it is a really good framework and I hope you would have the time to make it better. 

Kind Regards.

Karim Kouni.

**Comment by joachimmarder** [comment]
>  .... why it could not find the powershell.exe

Where is you PowerShell.exe located? 
Is this path part of the PATH env variable?
Does it work for you to execute powershell in the WIN+R dialog or at the command line without absolute path?

**Comment by karooma** [comment]
My path environment was indeed corrupted. Adding the path solves the problem.
Sorry for wasting your time.
