### ISSUE TITLE
Add history/source

### ISSUE THREAD

**Issue by gabr42** [TurboPack/RibbonFramework#5]
After a quick look around I couldn't find any reference to the original Ribbon Framework for Delphi project (http://www.bilsen.com/windowsribbon/index.shtml) which this repository is clearly based upon.

I think it would be fair to link to the original author.

**Comment by joachimmarder** [comment]
I was in close contact with the original author when I adopted the project. Doc\Readme.txt includes a link to the original page.

**Comment by joachimmarder** [comment]
Now the Reade.md file on top level also includes a link to Eric's page.
