### ISSUE TITLE
Fix/Enhancement: Ribbon designer hard wired to windows 7 sdk path settings

### ISSUE THREAD

**Issue by karooma** [TurboPack/RibbonFramework#51]
The ribbon designer code is partly hard wired to windows 7 sdk path settings and fails to work on windows 10.
I suggest to:
- Add an option to specify the path to windows power shell.
- Remove unnecessary checks for Delphi compiler inside the code as the user can specify that in the settings dialogue.
- Remove unnecessary checks for windows sdk path and tools and the download button as it is specific to windows 7 only.

Let me if I can be of any help.

Karim Kouni.

**Comment by joachimmarder** [comment]
> Add an option to specify the path to windows power shell.

As far as I know powershell.exe is in the PATH environment variable of a standard Windows installation. If it is missing there, it would be sufficient to add the path to the PATH variable. If PowerShell is causing a lot of trouble, it would be better to rewrite the code in Delphi and use it in the Ribbon Designer.

> Remove unnecessary checks for Delphi compiler inside the code as the user can specify that in the settings dialogue.

You mean in the PowerShell script? it does not use the Delphi Compiler. The PowerShell script was intended to be also used in Makefiles and in build scripts on build servers, where it might not have access to these settings. But again, the best solution could be to rewrite the code in Delphi and use it in the Ribbon Designer.

The Ribbon Designer does already support the command line option /BUILD.

> Remove unnecessary checks for windows sdk path and tools and the download button as it is specific to windows 7 only.

I don't see any benefit in removing the download button. Instead we should point to the Windows 8.1 on Windows 8 and higher.

> The ribbon designer code is partly hard wired to windows 7 sdk path settings and fails to work on windows 10.

I've added support for the Win8.1 SDK.

**Comment by karooma** [comment]
> As far as I know powershell.exe is in the PATH environment variable of a standard Windows installation. If it is missing there, it would be sufficient to add the path to the PATH variable. If PowerShell is causing a lot of trouble, it would be better to rewrite the code in Delphi and use it in the Ribbon Designer.

True. But sometimes the path environment variable can be corrupted by other softwares, actually delphi 10.1 berlin installation did that to many devs. So, letting the user input that is safer IMO. Besides, it is done only once.

> You mean in the PowerShell script? it does not use the Delphi Compiler. The PowerShell script was intended to be also used in Makefiles and in build scripts on build servers, where it might not have access to these settings. But again, the best solution could be to rewrite the code in Delphi and use it in the Ribbon Designer.

I found that in the ribbon designer code too. 

> I don't see any benefit in removing the download button. Instead we should point to the Windows 8.1 on Windows 8 and higher.

The link indeed points to windows 7 sdk, see screen shot below.

![win sdk link](https://cloud.githubusercontent.com/assets/20535050/17035839/7b062d20-4f81-11e6-86e6-a69bb6579349.png)

> I've added support for the Win8.1 SDK.

Much appreciated.

**Comment by joachimmarder** [comment]
> But sometimes the path environment variable can be corrupted by other softwares, actually delphi 10.1 berlin installation did that to many devs. So, letting the user input that is safer IMO. Besides, it is done only once.

PowerShell is used more and more nowadays. Forcing 100% to configure the path just because <1% of the users have a corrupted PATH variable does not seem right to me. Making the PowerShell script obsolete is also the best solution here, it just requires a little work.

**Comment by karooma** [comment]
agreed.

Good luck.
