### ISSUE TITLE
Ribbon designer - unstable behaviour

### ISSUE THREAD

**Issue by karooma** [TurboPack/RibbonFramework#52]
Using Version 2.2.1:

The attached file compiles fine but when preview is invoked. the designer crashes with a windows message: Ribbon designer stopped working.
[RibbonMarkup.zip](https://github.com/TurboPack/RibbonFramework/files/388718/RibbonMarkup.zip)

**Comment by joachimmarder** [comment]
I don't see any problem here using the unmodifed RibbonDesigner.exe of V2.2.1 on Windows 10, Delphi XE8, Windows 7 SDK UICC.exe

**Comment by joachimmarder** [comment]
Can you please send more details, like screenshots or call stacks?

**Comment by karooma** [comment]
I compiled the designer source using Delphi 10.1 berlin, Windows 10 sdk. Checking with the precompiled EXE, no problems so far. Weird.

**Comment by joachimmarder** [comment]
No problem with RibbonDesinger compiled with Delphi 10.1, and Windows 7 SDK. 

> Checking with the precompiled EXE, no problems so far.

Then please use precompiled Designer, that's why it is deployed as EXE.
