### ISSUE TITLE
Ribbon Designer - Changing to Views or XML Source tab when no file is loaded or with a blank xml file crashes the designer

### ISSUE THREAD

**Issue by karooma** [TurboPack/RibbonFramework#53]
Steps:
- Open Designer.
- Change tab from Commands to Views or XML sources.
- Designer crashes.

Attached call stack.

![app crash on tab change](https://cloud.githubusercontent.com/assets/20535050/17218828/25421a06-54e1-11e6-9e1d-a121a8ebed48.png)

**Comment by karooma** [comment]
Tested with the version from the master, AV still there.

**Comment by joachimmarder** [comment]
> Tested with the version from the master

Did you build your own EXE or did you use the one from master? I update the EXE only when an official release is done.

**Comment by karooma** [comment]
I used the binary EXE in version 2.2.1 not my own EXE.
