### ISSUE TITLE
The "F" letter of Application Menu not change even being configured another letter in Ribbon Designer's Keytip.

### ISSUE THREAD

**Issue by aj-brasaca** [TurboPack/RibbonFramework#57]
When we press "ALT" key the itens on Ribbon exposes some letters as shortcut. However, how to change the letter that appears on Application Menu ?

See picture below.

![application menu](https://cloud.githubusercontent.com/assets/8443207/18977688/d0b40e98-8692-11e6-947f-3fba7c3f910d.png)

**Comment by joachimmarder** [comment]
Not sure if that can be configured, that would be a general Windows Ribbon Framework question that you could ask at stackoverflow.com.

What letter does Windows Paint or Microsoft Movie Maker use there?

**Comment by aj-brasaca** [comment]
I guess you are right. Paint's portuguese version also has the "F" letter as shortcut on Application Menu. Nevermind. Thank you Joachim...
