### ISSUE TITLE
Is there something missing on site ?

### ISSUE THREAD

**Issue by aj-brasaca** [TurboPack/RibbonFramework#58]
Joachim...

The description on how to use the framework is actually correct and complete ? Because yesterday I spent 10 hours following the instructions on the site and redoing the project and can not bind controls to the code. I used the most common example (no Actions) without success.
I asked a question on Stackoverflow but no one answered so far (http://stackoverflow.com/questions/39999961/windows-ribbon-framework-for-delphi-fail-on-linking-to-commands). I did the following steps (I'm using Delphi 10.1 Berlin):

1. I jump this part (according to the instructions Delphi 10.1 don't need it)

    Go to "Project | Options".
    Go the the Application page.
    Uncheck "Enable runtime themes". Don't worry, your application will still be theme-aware because **we will use a custom manifest** (I did not find the informations for this !).
    
2. Choose "Project | Add to project...".
    In the File Open dialog box, choose the "Resource file (*.rc)" file type.
    Open the file "UIRibbon.rc" in the Lib directory of the Ribbon Framework.

3. Drop the TUIRibbon control from your RAD Studio toolbox on your main form.

4. Add the .PAS file created by the Ribbon Designed to the uses of your form. It is named equally to the XML file in which you saved the ribbon design.

OK. I compiled the source code and the Ribbon has been shown correctly.

5. I added the file "Ribbon\RibbonMarkup.pas" to the project and a "uses RibbonMarkup" on Implementation section of unit.

6. I pointed to the Ribbon Lib folder under "Options / Options / Delphi options / Library / Library Path. 

7. I declared in Type the functions:
   procedure RibbonLoaded;
   procedure CommandCreated(const Sender: TUIRibbon; const Command: TUICommand);

8. In private:
    FCmdCut  : TUICommandAction;
    FCmdCopy : TUICommandAction;
    procedure CutExecute(const Args: TUICommandActionEventArgs);
    procedure CopyExecute(const Args: TUICommandActionEventArgs);

9. The implementation of functions:

procedure TfrmPrincipal.CommandCreated(const Sender: TUIRibbon;
  const Command: TUICommand);
begin
  inherited;

  case Command.CommandId of

    CmdCut:
      begin
        FCmdCut := Command As TUICommandAction;
        FCmdCut.OnExecute := CutExecute;
      end;

    CmdCopy:
      begin
        FCmdCopy := Command As TUICommandAction;
        FCmdCopy.OnExecute := CopyExecute;
      end;

  end;
end;

procedure TfrmPrincipal.RibbonLoaded;
begin
  inherited;
  Color := ColorAdjustLuma(Ribbon.BackgroundColor, -25, False);
end;

procedure TfrmPrincipal.CopyExecute(const Args: TUICommandActionEventArgs);
begin
  pgcTelas.ActivePageIndex := 2;
end;

procedure TfrmPrincipal.CutExecute(const Args: TUICommandActionEventArgs);
begin
  pgcTelas.ActivePageIndex := 1;
end;

The controls do not run the code. Do I forgot something ? 

Adalberto José Brasaca
System Analyst
aj-brasaca@hotmail.com
Piracicaba - Brazil

**Comment by joachimmarder** [comment]
>The description on how to use the framework is actually correct and complete?

If I knew that something was incorrect or missing, I would have added it. So it's correct and complete by my best knowledge. Please keep in mind that I am not the original author.


> I used the most common example (no Actions) without success.

So far I used the ribbon control only with actions, and without problems. I find this is the easiest way. Do our sample projects work?

Please note that our issue tracker is intended to file bugs, it is not a support forum.

**Comment by aj-brasaca** [comment]
Joachim,

I run both Textpad example and it's fine. I included a Pagecontrol component and works the way I wanted. I don't understand... The only thing different is that in Project Manager, unlike my project and instructions of the site, the file UIRibbon.rc not appear.
The files that appear are from the Lib folder: UIRibbon.pas, UIRibbonApi.pas, UIRibbonCommands.pas, UIRibbonForm.pas, UIRibbonUtils.pas and WinApiEx.pas.

**Comment by joachimmarder** [comment]
> unlike my project and instructions of the site, the file UIRibbon.rc not appear.

Have you tried adding it?

**Comment by aj-brasaca** [comment]
Yes, without success. I'll try to modify the Textpad project that is working and see what happens.

**Comment by aj-brasaca** [comment]
Sorry, but I have to ask: Is it required a default name for things like image folder's name to be "res" and the name of main unit to be FMain?

**Comment by joachimmarder** [comment]
>  Is it required a default name for things like image folder's name to be "res" and the name of main unit to be FMain?

No, I don't have it that way in [TreeSize](https://github.com/TurboPack/RibbonFramework/wiki/References).

**Comment by aj-brasaca** [comment]
Joachim,

IT WORKS USING TACTIONS !!! But the Commands I defined as **Toggle Button** on Ribbon Designer become **Button** on executable. To change the button state to "checked" was necessary put the line "ButtonName.Checked := true;" inside Action code. Is that the only way ?

**Comment by joachimmarder** [comment]
I don't know. As I wrote before, I used only action mapped to commands by name. Many of the included samples show other ways. **Please note that our issue tracker is intended to file bugs, it is not a support forum.** If you think you found a bug, please include steps how to reproduce it, best using the included sample projects.
