### ISSUE TITLE
c++ Builder Berlin 10.1 (update 2) not work with TurboPack/RibbonFramework

### ISSUE THREAD

**Issue by matjak2** [TurboPack/RibbonFramework#62]
I created empty VCL Forms Application (C++ builder), On mainForm i put TUIRibbon and try to compile, 
First issue is that on Unit1.h is missing #include <UIRibbon.hpp> instead there is line with #include "UIRibbon.h" which is from  $(BDS)\include\windows\sdk\UIRibbon.h and seem to me that is generated from UIRibbon.idl.  if i put line #include <UIRibbon.hpp> after #include "UIRibbon.h" i can compile source. Then i added "SimpleRibbonUI.pas" from samples directory. I built project. when i run under debbuger i got 
"Project Project1.exe raised exception class EOleException with message "Unspecified error". if i click continue i got new error window with message: "An error occurred while trying to load Ribbon resource "APPLICATION": Unspecified error. 
I look Project1.exe with VisualStudio and this resources are visible:

![slika](https://cloud.githubusercontent.com/assets/25955719/23229389/6b4706de-f940-11e6-94ba-15a03d6ca30e.png)

binary data of APPLICATION_RIBBON looks like this:

![slika](https://cloud.githubusercontent.com/assets/25955719/23229435/971a91b8-f940-11e6-9175-12ff08f313a4.png)

Any Idea?

**Comment by joachimmarder** [comment]
The exception does not necessarily mean that the resource is not present. The error occurred inside the Ribbon Framework call `IUIFramework.Load()` which expects a resource name as parameter. The textual representation of the error message is "Unspecified error" which is not helpful at all. So I have now added the actual OLE error code to the exception message. Maybe this will help any further. Would you give it another try?

**Comment by joachimmarder** [comment]
Is there any news regarding this issue? Is it maybe fixed in RAD Studio Tokyo 10.2.1?

**Comment by joachimmarder** [comment]
No more feedback was posted since February, so I am closing this issue for now.
