### ISSUE TITLE
ExecuteLink is ignored for TUICommandAnchor

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#66]
I assigned a command to the Application menu tab, but it seems that ExecuteLink is ignored for TUICommandAnchor, I was not able to catch event "Tab opening/changing".

I'm trying to fill recent list at application menu tab clicking and/or to replace action completely on tab clicking. 
The same question i guess was at 43 issue (https://github.com/TurboPack/RibbonFramework/issues/43)

**Comment by joachimmarder** [comment]
Can you provide a sample project or detailed steps how to reproduce this with one of our sample projects?

**Comment by Nick74k** [comment]
Attached. The problem is that procedures TabHomeExecute, CMD_RecentExecute, CMD_ShowFilesExecute are never executed. May be there is another way to do this, but I find nothing about in documentation. 
(Not sure about CMD_RecentExecute - may be it will be called when recent item clicked, but how to fill it if I can't track tab opening?)

[RibTest.zip](https://github.com/TurboPack/RibbonFramework/files/1397290/RibTest.zip)

**Comment by joachimmarder** [comment]
I think the commands TabHomeExecute and  CMD_ShowFilesExecute are only used to provide the captions, they don't get executed. Typically the Windows Ribbon Frame works fires only commands if the user picked a true action, but not for opening menu or switching tabs.

What do you intend to do in those event handlers?

**Comment by joachimmarder** [comment]
> Not sure about CMD_RecentExecute - may be it will be called when recent item clicked

That's the case.

>but how to fill it if I can't track tab opening?

You can e.g. use the `OnUpdate` event of the corresponding Delphi action and call `UIRibbon.SetRecentItems()` or `TUIRibbon.AddToRecentItems()`. But I agree it is a little tricky and I just opened two new issues to improve this. The included TextPad samples include sample code for the recent files.

**Comment by Nick74k** [comment]
Oh, I see. Big thanks for answer.

Is it possible also to add event like OnTabChanging of TPageControl to TUIRibbon itself?
Or also use Action.OnUpdate for command, attached to menu tab. (Now it generates events on every mouse move over form - not sure what for).
I'm trying to replace application menu with my own form (Like it works in Microsoft office 2016), I mean something like this
```
procedure Ribbon.OnTabChanging( commandid: integer; var processed: boolean);
begin
  if commandid = CMD_AppMenu then begin
    processed:= true;
    ribbon.Visible := false;
    myownpanel.visible := true;
  end;
end  
```

**Comment by joachimmarder** [comment]
> Is it possible also to add event like OnTabChanging of TPageControl to TUIRibbon itself?

Seems possible but rather complicated:
https://msdn.microsoft.com/en-us/library/windows/desktop/jj662752%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

I just opened a new issue for this. Can we close this issue here?

**Comment by Nick74k** [comment]
Yes, big thanks for your work!!!!
