### ISSUE TITLE
If RecentFiles Command has not been created, cache the strings in a member variable

### ISSUE THREAD

**Issue by joachimmarder** [TurboPack/RibbonFramework#67]
Add this code to the OnShow event of your from:

```
procedure TForm5.FormShow(Sender: TObject);
begin
  Ribbon.AddToRecentItems('test1');
  Ribbon.AddToRecentItems('test2');
end;
``` 
It will result in an EAccessViolation because fRecentItem is `nil` because the ribbon control has not been created.

**Comment by Nick74k** [comment]
Just the same problem with first event of action CMD_RecentUpdate.
Ribbon.AddToRecentItems( '123' ); causes Access violation, but Ribbon.SetRecentItems( CMD_Recent, sl ); works well.
