### ISSUE TITLE
DoubleBuffered and TUIRibbon problem

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#69]
Main form with property DoubleBuffered = true causes window header to dissapear at minimizing of ribbon.
Test project attached.
[RibTest.zip](https://github.com/TurboPack/RibbonFramework/files/1400960/RibTest.zip)

**Comment by SaschaSchaefer** [comment]
I have reverted code that restricted repainting of the title bar to the first call of WMPaint. That restriction was meant to fix a very rare case in multi-monitor environments with different DPI settings, where the window was not drawn correctly. However, I could not reproduce it anymore, so I think the initial code (always redrawing the title) is correct.

I have seen one other case, where the title bar was not drawn correctly, so this should fix both issues.
