### ISSUE TITLE
Win64 and TUIRibbon

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#72]
Just wish.

Now designer and run-time parts are both in one package for delphi, but DesignerIDE module exists only for win32 projects, so it is not possible to add TUIRibbon to win64 project - element is grayed.
The small hack is to switch to win32, add TUIRibbon and switch back to win64, or copy TUIRibbon in win32 project and past it into win64 project - all works well.
Embarcadero advises to split package to design part and runtime part for using components in both platforms simultaneously.

**Comment by joachimmarder** [comment]
Which Delphi version do you use? It works as expected in !0.2 Tokyo, but I think older Delphi versions were buggy here.

**Comment by Nick74k** [comment]
I have 10.2.
Steps to reproduce:
1. Create new VCL project
2. Add platform 64 bit and switch to it
3. Try to add component TUIRibbon to the form - it is grayed.
