### ISSUE TITLE
Add property for RibbonDesigner with path to XML file

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#73]
Please add parameter with file name for RibbonDesigner at opening it from Delphi IDE (Double click on TUIRibbon) to skip need of pressing "Open file" and selecting file every time.
Add file name as published property, if it cannot be taken automatically from form itself.

**Comment by joachimmarder** [comment]
I tried that earlier with no luck. The problem is that the TUIRibbon does not know the source XML file name or the generated Pascal file at designtime. Opening the RibbonDesigner is possible using the right click menu in the designer.

**Comment by Nick74k** [comment]
Then just add published property for UIRibbon - path to XML file for DesignerEditor. It will be more convenient to use it then - opening designer without file have no sense.
Not sure is it possible to show file dialog at opening with not assigned property and save file name to it automatically - smth like this
```
procedure TMyRibbonFrameworkEditor.ExecuteVerb(pIndex: Integer);
var
  lRibbon: TUIRibbon;
  dlg: TOpenDialog;
begin
  inherited;
  lRibbon := (Self.Component as TUiRibbon);
  if not Assigned (lRibbon.FDesignerXMLPath) then begin
    dlg := TOpenDialog.Create( nil );
    try
      dlg.Filter := 'XML files|*.xml';
      if not dlg.Execute then exit;
      lRibbon.DesignerXMLPath := dlg.FileName;
    finally
      dlg.free;
    end;
  end;
  case pIndex of
    0: ShellExecute(0, 'open', PChar(GetDesignerPath() + ' "' + lRibbon.DesignerXMLPath + '"'), nil, nil, SW_SHOWNORMAL);
  end;
end;
```

**Comment by joachimmarder** [comment]
> Then just add published property for UIRibbon - path to XML file for DesignerEditor. 

A kind of designtime-only property? Somewhat uncommon, but should work.

**Comment by joachimmarder** [comment]
Implemented. Let meknow what you think, did not have much time for testing today.

**Comment by Nick74k** [comment]
Wonderful. Some changes to your functions - marked with long arrows in comments.
Added initial dir for current project, added project path in two places and two ShowMessages removed.
Not sure that relative paths are good enough - what will be if ribbon files are located outside of project path? Then we need some additional checks if the specified file name is relative or not to check - is it needed to add project path.

Besides that there is a small problem - changing of published property (lRibbon.RibbonSourceFile := BrowseForXmlFile();) does not mark file as changed, so if unit was saved before and closed right after this operation, property value will not be saved - Delphi thinks that nothing changed.
Dont know is there exist some function like unit.Touch() to mark unit as changed.

```
function BrowseForXmlFile(): string;
begin
  With TOpenDialog.Create(nil) do
    try
      Filter := 'XML files|*.xml';
      InitialDir := ExtractFilePath( getActiveProject.FileName );   // <------------------------------------
      if not Execute then
        Exit;
      Result := FileName;
    finally
      Free;
    end;
  // Make the path relative tothe project, so the the settings is portable
  Result :=  ExtractRelativePath(getActiveProject.FileName, Result);
//  ShowMessage(getActiveProject.FileName);                        // <------------------------------------   
//  ShowMessage(Result);                                           // <------------------------------------
end;

procedure TMyRibbonFrameworkEditor.ExecuteVerb(pIndex: Integer);
var
  lRibbon: TUIRibbon;
begin
  inherited;
  lRibbon := (Self.Component as TUiRibbon);
  if lRibbon.RibbonSourceFile.IsEmpty or 
     not FileExists(ExtractFilePath(getActiveProject.FileName)+'\'+lRibbon.RibbonSourceFile) then   // <------------------------------------
    lRibbon.RibbonSourceFile := BrowseForXmlFile();
  case pIndex of
    0: ShellExecute(0, 'open', PChar(GetDesignerPath()),
   PChar('"'+ExtractFilePath(getActiveProject.FileName)+'\'+lRibbon.RibbonSourceFile+'"'), nil, SW_SHOWNORMAL);  // <------------------------------------
  end;
end;
```

**Comment by joachimmarder** [comment]
Placing the XML file outside the project dir sounds like a strange idea. I used absolute paths at first (which lead to the wrong code in the commt), but with absolute paths a projects is not portable any more, so this is a no-go. Thanks for your feedback.
