### ISSUE TITLE
Visible - header region

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#74]
Setting Ribbon.Visible to false at run time causes ribbon to hide, but client area of form then overlaps the header of the window. Example attached.
[RibTest.zip](https://github.com/TurboPack/RibbonFramework/files/1401602/RibTest.zip)

**Comment by SaschaSchaefer** [comment]
Should be fixed now. Setting the visibility to "False" should now work correctly regardless of when it is called.
