### ISSUE TITLE
TUIRibbon and TToolbar

### ISSUE THREAD

**Issue by ivancx** [TurboPack/RibbonFramework#77]
When using TUIRibbonFramework from https://github.com/TurboPack/RibbonFramework and having TToolBar with few TToolButtons on a form, TToolButtons are not visible after UIRibbon Load. Somehow UIRibbon Framework hides them. They are not destroyed, their visible propery is true, but cannot be visible (shown).

**Comment by joachimmarder** [comment]
Which version are you using?
Can you please attach a screenshot to the issue?

I modified the included sample project "Samples\High Level\07 Text Pad with Action List\TextPad.dproj" and added a toolbar. All looked as expected:
![grafik](https://user-images.githubusercontent.com/10615289/33395134-d64e0208-d544-11e7-8418-336c21cdc307.png)

**Comment by joachimmarder** [comment]
Any updates on this issue? Otherwise I will close it.

**Comment by joachimmarder** [comment]
No response from report, so closing this issue.
