### ISSUE TITLE
AppMode <>0 at application start

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#79]
I can't set application mode at program start without flickering - I tried Ribbon.OnLoaded, Form.OnCreate, Form.OnShow - I always see ribbon in appmode 0, changing to needed mode in some short time, can you advise the way to do this without showing AppMode 0 first?

**Comment by joachimmarder** [comment]
I can confirm this. Can be reprodcued with "Samples\High Level\07 Text Pad with Action List\TextPad.dproj" by adding `Ribbon.ApplicationModes := [1];` to the `OnCreate` or `OnShow` event handler.

The best solution is to design Application Mode 0 as initial AppMode for your ribbon.

I found that if setting the application mode is followed by a call to `Application.ProcessMessages()` the situation improves.

**Comment by Nick74k** [comment]
It's hard - my application checks license at startup and shows either full ribbon or ribbon with only one tab "registration".
The only way to remove unused controls at startup is to make 0 mode empty at all.

**Comment by joachimmarder** [comment]
I will close this issue as there is nothing we can do about it and a workaround exists.
