### ISSUE TITLE
 Showmessage does not appear from a linked action

### ISSUE THREAD

**Issue by VictorJGarciaMartin** [TurboPack/RibbonFramework#80]
In this case, when you press the ribbon button, the showmesages are not displayed

The delphi version used is 10.2.2

Any suggestions?

![image](https://user-images.githubusercontent.com/32029675/34380546-91309748-eb02-11e7-931f-25d30fadbefc.png)

![image](https://user-images.githubusercontent.com/32029675/34380520-4d3fd972-eb02-11e7-82da-baee8becf468.png)

![image](https://user-images.githubusercontent.com/32029675/34380528-6c20f3d0-eb02-11e7-95a8-7a515f87b759.png)

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting issues shown on the project homepage. Can you send a sample project that replicates the issue?

**Comment by joachimmarder** [comment]
No reaction from reporter => Close
