### ISSUE TITLE
Ribbon Framework does not load when setting vcl style in main form create

### ISSUE THREAD

**Issue by markwilliams1234** [TurboPack/RibbonFramework#81]
The framework loads absolutely fine until I add the following code to my main form's create event:

```
AStyle:=GetValueFromWinRegistry(HKEY_CURRENT_USER, winRegistryKey, 'ActiveTheme');
if AStyle<>'' then
  TStyleManager.trySetStyle(AStyle);

```
For some reason setting the style at this point causes the loading of the ribbon to crash.

It crashes on line 1018 of UIRibbon.load ie 

> FFramework.LoadUI(Inst, PChar(FResourceName + '_RIBBON'));

At this point FResourceName is "APPLICATION". I have checked if that resource has been created at that point and it has in either case (ie whether I am trying to set the style or not).

Presumably set style is doing something which is causing a problem with the framework loading, but I have failed to get to the bottom o fit.

**Comment by joachimmarder** [comment]
It should work if you call `TrySetStyle()`before creating the form. I don't think this is a bug in our wrapper or something that we can handle there. Please post the full call stack of the exception.

**Comment by markwilliams1234** [comment]
Excellent. That worked. Thanks very much
