### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by aj-brasaca** [TurboPack/RibbonFramework#82]
Clicking the **System Menu** on a form that has the Ribbon Control causes **Access Violation**.

**Comment by joachimmarder** [comment]
Please respect our guidelines for submitting bugs shown on the project homepage:

> IMPORTANT: Before submitting bugs, make sure you are using the latest version. When submitting bugs, please include a screenshot of the problem or the exact error messages and exception call stacks, and a sample project or steps how to replicate the problem with one of the included sample projects.

**Comment by joachimmarder** [comment]
No feedback from reporter. Please try latest version.
