### ISSUE TITLE
Application Menu - won't go away

### ISSUE THREAD

**Issue by markwilliams1234** [TurboPack/RibbonFramework#87]
If you set the command for Application Menu to none and remove child commands, it still appears on the ribbon. If you try and delete the application men in views, it seems to process the delete command (or at least it processes without grumbling), but the Application Menu remains. Is this intended?

**Comment by markwilliams1234** [comment]
Just use any of the sample apps eg TextPad. You'll see what I mean when you try to delete the Application Menu and you will notice in preview it will still show the Application Menu even if no command associated with it.

**Comment by SaschaSchaefer** [comment]
I'm afraid the Application Menu cannot be removed. The official documentation states: 
> The Application Menu is a mandatory element in any Ribbon application

(https://docs.microsoft.com/en-us/windows/desktop/windowsribbon/windowsribbon-controls-applicationmenu)

**Comment by markwilliams1234** [comment]
OK. Thanks for letting me know.

 

__
