### ISSUE TITLE
Localization of ctGroup elements with Action

### ISSUE THREAD

**Issue by Nick74k** [TurboPack/RibbonFramework#92]
Is it possible to add TUICommandType.ctGroup to the procedure DoCommandCreated? (Marked added line with arrow)
The idea is to localize whole ribbon with delphi property localizer, ctGroup is the only command which doesn't try to match with ActionList of Delphi now.

```
procedure TUIRibbon.DoCommandCreated(const pCommand: TUICommand);
const
  sNoMappingFound = 'Action "%s" that maps to Ribbon command with ID %d was not found! Please ensure to update your Ribbon.Markup.xml file if you have renamed an Action.';
var
  lMarkupItem : TRibbonMarkupElement;
  lAction     : TCustomAction;
begin
  if pCommand.CommandType = TUICommandType.ctRecentItems then
    fRecentItems := (pCommand as TUICommandRecentItems);
  // When a Ribbon command is created, we check if there is a corresponding
  // TAction element available. If so, we assign the properties of that action
  // (Caption, Hint, etc.) to that ribbon element.
  if Assigned(Self.RibbonMapper) and Self.RibbonMapper.TryGetItem(pCommand.CommandId, lMarkupItem) then begin// Get the corresponding TAction for the given Ribbon command
    case pCommand.CommandType of
      TUICommandType.ctAction,
      TUICommandType.ctDecimal,
      TUICommandType.ctBoolean,
      TUICommandType.ctColorAnchor,
      TUICommandType.ctCollection,
      TUICommandType.ctFont,
      TUICommandType.ctRecentItems:
      begin
        lAction := Self.GetActionForCommand(pCommand);
        if Assigned(lAction) then
          pCommand.Assign(lAction)
        {$ifdef DEBUG}else if pCommand.CommandType in [TUICommandType.ctAction, TUICommandType.ctBoolean] then
          OutputDebugString(PChar(Format(sNoMappingFound, [lMarkupItem.Name, pCommand.CommandId]))){$endif};
      end;
      // Try mapping ctAnchor (Tabs) to an action. If found, assign properties.
      // If not found, at least try to localize it.
      TUICommandType.ctAnchor,
--->  TUICommandType.ctGroup: begin
        lAction := Self.GetActionForCommand(pCommand);
        if Assigned(lAction) then
          pCommand.Assign(lAction)
        else
          Self.LocalizeRibbonElement(pCommand, lMarkupItem);
      end;// ctAnchor
    else
      // If none of the types above, at least try to localize that command by
      // extracting the corresponding resource strings from the resource file.
      Self.LocalizeRibbonElement(pCommand, lMarkupItem);
    end;// case/else
  end;// if RibbonMapper
  if Assigned(FOnCommandCreate) then
    FOnCommandCreate(Self, pCommand);
end;
```

**Comment by Nick74k** [comment]
Seems to work well except Application Menu.. :-/

**Comment by joachimmarder** [comment]
We recently revised this, see commit c590a51. Could you please try if the GitHub master works better for you?

**Comment by Nick74k** [comment]
Thanks! Checked last source.
The same two problems - two elements are not localized via TAction.Caption change:
1. Recent items caption - ignores TAction.Caption, initial value taken from command property of recent command of Ribbon designer.
2. Application menu - ignores both assigned command caption and assigned TAction.caption, didn't find how to change initial value "File" at all.

**Comment by SaschaSchaefer** [comment]
I found a stackoverflow post with the same question: [https://stackoverflow.com/questions/43588413/customize-applicationmenu-button-in-windows-ribbon-framework-for-delphi](url)

I also don't think it is possible to change the application menu caption. The API documentation states:

> Note  Windows 8 and newer: Application Menu button image changed to label: **File**. We recommend that you do not use File as the label for any of your own tabs.
(https://msdn.microsoft.com/en-us/library/windows/desktop/dd940489(v=vs.85).aspx)

It also states that `UI_PKEY_TooltipDescription `and `UI_PKEY_TooltipTitle `are the only two properties that are available for this command type. I'm afraid there's nothing we can do to change this, sorry.


I also tested the "recent items" menu. For me, it worked as expected, unless I explicitly defined a caption in the ribbon designer, in which case the Action's caption would simply be ignored. The action's caption is applied to the command correctly like for any other command, but for some reason the framework does not update the ribbon control accordingly, if there was already a caption defined in the markup.

An easy workournd would be not to define a caption in the ribbon designer and only use the action's caption. I'm not sure if there's a "real" fix for this.

**Comment by Nick74k** [comment]
Thanks! Recent items is working now.

Tried to change language of EXE at start with smth like this to change the language of "File", but didn't succeed.
```
SetProcessPreferredUILanguages( MUI_LANGUAGE_ID, '0409', @pl );
SetThreadPreferredUILanguages( MUI_LANGUAGE_NAME, 'en-US', nil);
SetThreadUILanguage( $409 );
```

**Comment by Nick74k** [comment]
May be, but requirement of other language pack installation is not a best idea imho.
Well, thanks for help, I guess we can close this issue..
